Import dhcp_probe v1.0.7
Signed-off-by: Joachim Wiberg <troglobit@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1622,7 +1622,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=dhcp_probe
- VERSION=1.0.6
+ VERSION=1.0.7
 
 
 cat >>confdefs.h <<_ACEOF
@@ -6534,6 +6534,94 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+
+
+
+ac_safe_struct=`echo "arpreq" | sed 'y%./+-%__p_%'`
+ac_safe_member=`echo "arp_dev" | sed 'y%./+-%__p_%'`
+ac_safe_all="ac_cv_struct_${ac_safe_struct}_has_${ac_safe_member}"
+  ac_uc_define=STRUCT_`echo "${ac_safe_struct}_HAS_${ac_safe_member}" | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+
+echo "$as_me:$LINENO: checking for arpreq.arp_dev" >&5
+echo $ECHO_N "checking for arpreq.arp_dev... $ECHO_C" >&6
+if eval "test \"\${$ac_safe_all+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+if test "x" = "x"; then
+  defineit="= 0"
+elif test "x" = "xno"; then
+  defineit=""
+else
+  defineit=""
+fi
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <net/if_arp.h>
+
+int
+main ()
+{
+
+struct arpreq testit;
+testit.arp_dev $defineit;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "${ac_safe_all}=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "${ac_safe_all}=no"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+
+fi
+
+
+if eval "test \"x$`echo ${ac_safe_all}`\" = \"xyes\""; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  cat >>confdefs.h <<_ACEOF
+#define $ac_uc_define 1
+_ACEOF
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
 echo "$as_me:$LINENO: checking for sys_nerr" >&5
 echo $ECHO_N "checking for sys_nerr... $ECHO_C" >&6
 if test "${ac_cv_var_sys_nerr+set}" = set; then
@@ -6945,6 +7033,78 @@ echo "$as_me:$LINENO: result: $ac_cv_have_ether_ntoa_proto" >&5
 echo "${ECHO_T}$ac_cv_have_ether_ntoa_proto" >&6
 	if test $ac_cv_have_ether_ntoa_proto = yes ; then
 		ac_tr_func=HAVE_`echo ether_ntoa | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'`_PROTO
+		cat >>confdefs.h <<_ACEOF
+#define $ac_tr_func 1
+_ACEOF
+
+	fi
+
+
+
+
+echo "$as_me:$LINENO: checking for ether_ntohost function prototype in netinet/ether.h" >&5
+echo $ECHO_N "checking for ether_ntohost function prototype in netinet/ether.h... $ECHO_C" >&6
+if test "${ac_cv_have_ether_ntohost_proto+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <netinet/ether.h>
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "ether_ntohost" >/dev/null 2>&1; then
+  ac_cv_have_ether_ntohost_proto=yes
+else
+  ac_cv_have_ether_ntohost_proto=no
+fi
+rm -f conftest*
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_ether_ntohost_proto" >&5
+echo "${ECHO_T}$ac_cv_have_ether_ntohost_proto" >&6
+	if test $ac_cv_have_ether_ntohost_proto = yes ; then
+		ac_tr_func=HAVE_`echo ether_ntohost | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'`_PROTO
+		cat >>confdefs.h <<_ACEOF
+#define $ac_tr_func 1
+_ACEOF
+
+	fi
+
+
+
+
+echo "$as_me:$LINENO: checking for ether_hostton function prototype in netinet/ether.h" >&5
+echo $ECHO_N "checking for ether_hostton function prototype in netinet/ether.h... $ECHO_C" >&6
+if test "${ac_cv_have_ether_hostton_proto+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <netinet/ether.h>
+
+_ACEOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  $EGREP "ether_hostton" >/dev/null 2>&1; then
+  ac_cv_have_ether_hostton_proto=yes
+else
+  ac_cv_have_ether_hostton_proto=no
+fi
+rm -f conftest*
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_ether_hostton_proto" >&5
+echo "${ECHO_T}$ac_cv_have_ether_hostton_proto" >&6
+	if test $ac_cv_have_ether_hostton_proto = yes ; then
+		ac_tr_func=HAVE_`echo ether_hostton | tr 'abcdefghijklmnopqrstuvwxyz' 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'`_PROTO
 		cat >>confdefs.h <<_ACEOF
 #define $ac_tr_func 1
 _ACEOF
